# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsspu',
            name='goods_id',
            field=models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='home.Goods', verbose_name='关联商品编号'),
        ),
    ]
