# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='account.Member', verbose_name='关联用户编号'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='goods_id',
            field=models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='home.Goods', verbose_name='关联商品编号'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='account.Member', verbose_name='关联用户编号'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='account.Member', verbose_name='关联用户编号'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='account.Member', verbose_name='关联用户编号'),
        ),
        migrations.AlterField(
            model_name='memberloc',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='account.Member', verbose_name='关联用户编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='goods_id',
            field=models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='home.Goods', verbose_name='关联商品编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='account.Member', verbose_name='关联用户编号'),
        ),
        migrations.AlterField(
            model_name='review',
            name='goods_id',
            field=models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='home.Goods', verbose_name='关联商品编号'),
        ),
        migrations.AlterField(
            model_name='review',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='account.Member', verbose_name='关联用户编号'),
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='goods_id',
            field=models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='home.Goods', verbose_name='关联商品编号'),
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='account.Member', verbose_name='关联用户编号'),
        ),
    ]
