# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190121_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='conten',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='member_img',
            field=models.ImageField(blank=True, null=True, upload_to='upload/member/', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='pay_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='real_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='真是姓名'),
        ),
    ]
